// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH3Q5mTFHh1ETNHsb-vmp_r4BIbJZeXB8',
    appId: '1:356811794340:web:c3f531e6afcff1dc78c331',
    messagingSenderId: '356811794340',
    projectId: 'first-todo-app-9550d',
    authDomain: 'first-todo-app-9550d.firebaseapp.com',
    storageBucket: 'first-todo-app-9550d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDygof1lZSe1XitYoj4xEHQewCFoyoeKcM',
    appId: '1:356811794340:android:769c621c7cea223678c331',
    messagingSenderId: '356811794340',
    projectId: 'first-todo-app-9550d',
    storageBucket: 'first-todo-app-9550d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9YBHZlqrUsVHcL_1XI6wBxPHebbLiWSU',
    appId: '1:356811794340:ios:7b7c4d91183d869b78c331',
    messagingSenderId: '356811794340',
    projectId: 'first-todo-app-9550d',
    storageBucket: 'first-todo-app-9550d.appspot.com',
    iosBundleId: 'com.killerdevil127.firstTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9YBHZlqrUsVHcL_1XI6wBxPHebbLiWSU',
    appId: '1:356811794340:ios:7b7c4d91183d869b78c331',
    messagingSenderId: '356811794340',
    projectId: 'first-todo-app-9550d',
    storageBucket: 'first-todo-app-9550d.appspot.com',
    iosBundleId: 'com.killerdevil127.firstTodoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH3Q5mTFHh1ETNHsb-vmp_r4BIbJZeXB8',
    appId: '1:356811794340:web:df870edd6380c8b178c331',
    messagingSenderId: '356811794340',
    projectId: 'first-todo-app-9550d',
    authDomain: 'first-todo-app-9550d.firebaseapp.com',
    storageBucket: 'first-todo-app-9550d.appspot.com',
  );
}